title: RobustScience
subtitle:
description:

url: ""
baseurl: ""

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
